language: node_js
node_js:
  - "4.2.2"
  - "6"

services:
  - redis-server

before_install:
  - rvm install 2.2.2

before_script:
  - npm run sass
  - NODE_ENV='ci' npm start&

script:
  - npm run test:ci
  - npm run test:acceptance
