app:
  build: .
  environment:
  - NODE_ENV=docker-compose
  - EMAIL_HOST=localhost
  - EMAIL_PORT=25
  - EMAIL_IGNORE_TLS=true
  - CASEWORKER_SOMEONEELSE_EMAIL=a@user.com
  - CASEWORKER_LOSTSTOLEN_EMAIL=a@user.com
  - CASEWORKER_ERROR_EMAIL=a@user.com
  - CASEWORKER_DELIVERY_EMAIL=a@user.com
  - CASEWORKER_COLLECTION_EMAIL=a@user.com
  ports:
  - "8080:8080"
  volumes:
  - "/public"
  net: "host"
maildev:
  image: djfarrelly/maildev
  net: "host"
  ports:
  - "80"
  - "25"

